//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.29 at 09:16:17 PM COT 
//


package ec.edu.espe.arqsoftware.examen.zuniga.server.ws;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ec.edu.espe.arqsoftware.examen.zuniga.server.ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ec.edu.espe.arqsoftware.examen.zuniga.server.ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ObtenerPartidosRequest }
     * 
     */
    public ObtenerPartidosRequest createObtenerPartidosRequest() {
        return new ObtenerPartidosRequest();
    }

    /**
     * Create an instance of {@link ObtenerPartidosResponse }
     * 
     */
    public ObtenerPartidosResponse createObtenerPartidosResponse() {
        return new ObtenerPartidosResponse();
    }

    /**
     * Create an instance of {@link PartidoRS }
     * 
     */
    public PartidoRS createPartidoRS() {
        return new PartidoRS();
    }

    /**
     * Create an instance of {@link ObtenerLocalidadesRequest }
     * 
     */
    public ObtenerLocalidadesRequest createObtenerLocalidadesRequest() {
        return new ObtenerLocalidadesRequest();
    }

    /**
     * Create an instance of {@link ObtenerLocalidadesResponse }
     * 
     */
    public ObtenerLocalidadesResponse createObtenerLocalidadesResponse() {
        return new ObtenerLocalidadesResponse();
    }

    /**
     * Create an instance of {@link LocalidadRS }
     * 
     */
    public LocalidadRS createLocalidadRS() {
        return new LocalidadRS();
    }

    /**
     * Create an instance of {@link CompraRequest }
     * 
     */
    public CompraRequest createCompraRequest() {
        return new CompraRequest();
    }

    /**
     * Create an instance of {@link CompraResponse }
     * 
     */
    public CompraResponse createCompraResponse() {
        return new CompraResponse();
    }

}
